### ISSUE TITLE
Let's change the README.md file

### ISSUE THREAD

**Issue by zampolli75** [zampolli75/isds1102slackbot#1]
Let's add a description in the README.md file.
Maybe type something like (Feel free to write your vision for the bot :-) ): "This is a bot for an Introduction to IS course. The bot will allow students to get information about the course schedule, checkups, and homework. Furthermore, it will push useful information to students depending on their personal behavior, personality, and current grade"...

To do this you will have to modify the file we created last time, then `add` those files to get them ready to be committed. After you `add` them you can create the `commit`. Finally, once you commit it you can `push` it to Github where you will see the change immediatly. 

Try to do it by yourself if you can using the a git cheatsheet. The main actions you have to undergo are the ones above.

**Comment by zampolli75** [comment]
fc1e758f25f6213ed79de448d46a7698d1e63404

**Comment by walter-scott** [comment]
Got it
